<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ensure.That" Version="10.1.0" />
    <PackageReference Include="Hl7.Fhir.Serialization" Version="$(Hl7FhirVersion)" />
    <PackageReference Include="Hl7.Fhir.Support.Poco" Version="$(Hl7FhirVersion)" />
    <PackageReference Include="Hl7.FhirPath" Version="$(Hl7FhirVersion)" />
    <PackageReference Include="JsonSchema.Net" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ValueSets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Health.Fhir.SourceNodeSerialization\Microsoft.Health.Fhir.SourceNodeSerialization.csproj" />
  </ItemGroup>

</Project>
