<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ignixa.FhirFakes.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Core/Ignixa.Specification/Ignixa.Specification.csproj" />
    <ProjectReference Include="../../src/Core/Ignixa.Serialization/Ignixa.Serialization.csproj" />
  </ItemGroup>

</Project>
