// -------------------------------------------------------------------------------------------------
// Copyright (c) Ignixa Contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System.Text.Json.Nodes;
using Ignixa.Abstractions;
using Ignixa.PackageManagement.Infrastructure;
using Ignixa.PackageManagement.Models;
using Ignixa.Serialization.SourceNodes;
using Ignixa.Specification.Generated;
using Ignixa.Validation;
using Ignixa.Validation.Abstractions;
using Ignixa.Validation.Schema;
using Ignixa.Validation.Services;
using Ignixa.Validation.Tests.TestHelpers.Packages;
using Shouldly;
using Xunit;
using Xunit.Abstractions;

namespace Ignixa.Validation.Tests.CustomerScenarios;

/// <summary>
/// End-to-end slicing proof against the real US Core 6.1.0 <c>us-core-patient</c> profile, whose
/// <c>Patient.extension</c> is sliced by a <c>value</c> discriminator on <c>url</c> (race / ethnicity
/// / birthsex, each 0..1). The profile's shipped snapshot is <b>stripped</b> so the snapshot is
/// regenerated by the M1/M2 <see cref="Ignixa.PackageManagement.Infrastructure.Snapshot.SnapshotGenerator"/>
/// — proving snapshot generation, the differential→snapshot adapter, and <c>SlicingCheck</c> work
/// together on a real differential IG profile.
/// </summary>
[Trait("Category", "RequiresNetwork")]
public sealed class UsCorePatientSlicingScenarioTests(ITestOutputHelper output)
{
    private const string ValidInputFile = "TestData/CustomerScenarios/us-core-patient-valid.json";
    private const string ProfileCanonical = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient";
    private const string RaceExtUrl = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race";

    private readonly ITestOutputHelper _output = output;
    private readonly R4CoreSchemaProvider _base = new();

    /// <summary>
    /// Builds a resolver from US Core with the <c>us-core-patient</c> snapshot removed, forcing the
    /// pipeline to regenerate it from the differential + base (M2), then adapt and build checks.
    /// </summary>
    private async Task<ProfileAwareValidationSchemaResolver> BuildDifferentialOnlyResolverAsync(CancellationToken cancellationToken)
    {
        var pkg = await TestFhirPackageLoader.LoadUsCoreAsync(cancellationToken);
        var resources = pkg.Resources.Select(StripSnapshotIfUsCorePatient).ToList();

        var packageSchema = new ProfileLayeredSchemaProvider(_base, resources);
        var packageVs = new PackageValueSetSource(resources);
        var terminology = new InMemoryTerminologyService(
            primary: _base.ValueSetProvider,
            additional: new[] { (IValueSetProvider)packageVs });
        var inner = new StructureDefinitionSchemaResolver(packageSchema, terminologyService: terminology);
        return new ProfileAwareValidationSchemaResolver(new CachedValidationSchemaResolver(inner));
    }

    private static ExtractedResource StripSnapshotIfUsCorePatient(ExtractedResource resource)
    {
        if (resource.ResourceType != "StructureDefinition"
            || !string.Equals(resource.Canonical, ProfileCanonical, StringComparison.Ordinal))
        {
            return resource;
        }

        var sd = (JsonNode.Parse(resource.ResourceJson) as JsonObject)!;
        sd.Remove("snapshot");
        return resource with { ResourceJson = sd.ToJsonString() };
    }

    private IElement ToElement(JsonNode json) => JsonNodeSourceNode.Create(json).ToElement(_base);

    private static IReadOnlyList<ValidationIssue> SlicingIssues(ValidationResult result)
        => result.Issues.Where(i => i.Code.StartsWith("slicing", StringComparison.Ordinal)).ToList();

    private void Dump(ValidationResult result, string label)
    {
        _output.WriteLine($"--- {label} ---");
        foreach (var i in SlicingIssues(result))
        {
            _output.WriteLine($"  [{i.Severity}] {i.Code} @ {i.Path}: {i.Message}");
        }
    }

    [Fact]
    public async Task GivenConformantUsCorePatient_WhenSnapshotRegeneratedAndValidatedAtFullDepth_ThenNoSlicingErrors()
    {
        var resolver = await BuildDifferentialOnlyResolverAsync(CancellationToken.None);
        var json = JsonNode.Parse(await File.ReadAllTextAsync(ValidInputFile, CancellationToken.None))!;
        var element = ToElement(json);

        var schema = resolver.ResolveForElement(element);
        schema.ShouldNotBeNull();

        var result = schema!.Validate(element, new ValidationSettings { Depth = ValidationDepth.Full }, ValidationState.ForRoot(element));

        Dump(result, "conformant us-core-patient (regenerated snapshot)");
        SlicingIssues(result)
            .Where(i => i.Severity is IssueSeverity.Error or IssueSeverity.Fatal)
            .ShouldBeEmpty("a conformant US Core Patient must not trip any slice rule");
    }

    [Fact]
    public async Task GivenUsCorePatientWithDuplicateRaceExtension_WhenValidatedAtFullDepth_ThenRejectedNamingRaceSlice()
    {
        var resolver = await BuildDifferentialOnlyResolverAsync(CancellationToken.None);
        var json = (JsonNode.Parse(await File.ReadAllTextAsync(ValidInputFile, CancellationToken.None)) as JsonObject)!;

        // Add a second us-core-race extension: race is a 0..1 slice, so this violates the slice max.
        var extensions = (json["extension"] as JsonArray)!;
        extensions.Add(new JsonObject
        {
            ["url"] = RaceExtUrl,
            ["extension"] = new JsonArray(new JsonObject { ["url"] = "text", ["valueString"] = "Declined" }),
        });

        var element = ToElement(json);
        var schema = resolver.ResolveForElement(element);
        schema.ShouldNotBeNull();

        var result = schema!.Validate(element, new ValidationSettings { Depth = ValidationDepth.Full }, ValidationState.ForRoot(element));

        Dump(result, "duplicate race us-core-patient");
        SlicingIssues(result).ShouldContain(
            i => i.Code == "slicing-cardinality" && i.Severity == IssueSeverity.Error && i.Message.Contains("race", StringComparison.Ordinal),
            "a second us-core-race extension must be rejected against the 0..1 'race' slice");
    }
}
