<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>xUnit integration for FHIR TestScript execution engine</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ignixa.TestScript\Ignixa.TestScript.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.extensibility.core" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
  </ItemGroup>

</Project>
