// <auto-generated />
// <copyright file="CompartmentType.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

// Generated from FHIR R4 ValueSet: http://hl7.org/fhir/ValueSet/compartment-type

using Ignixa.Serialization;

namespace Ignixa.Specification.ValueSets.Normative;

/// <summary>
/// Which type a compartment definition describes.
/// </summary>
public enum CompartmentType
{
    [EnumLiteral("Device", "http://hl7.org/fhir/compartment-type")]
    Device,
    [EnumLiteral("Encounter", "http://hl7.org/fhir/compartment-type")]
    Encounter,
    // Note: "Group" is used by CompartmentDefinition-group.json in the FHIR R6 ballot4 package,
    // but is NOT (yet) listed in that same package's CodeSystem-compartment-type.json --
    // a confirmed inconsistency in HL7's ballot4 content, not a tooling gap. Added by hand
    // pending upstream correction.
    [EnumLiteral("Group", "http://hl7.org/fhir/compartment-type")]
    Group,
    [EnumLiteral("Patient", "http://hl7.org/fhir/compartment-type")]
    Patient,
    [EnumLiteral("Practitioner", "http://hl7.org/fhir/compartment-type")]
    Practitioner,
    [EnumLiteral("RelatedPerson", "http://hl7.org/fhir/compartment-type")]
    RelatedPerson,
}
