<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sparky.Domain\Sparky.Domain.csproj" />
    <ProjectReference Include="..\Sparky.Search\Sparky.Search.csproj" />
    <ProjectReference Include="..\Sparky.Specification\Sparky.Specification.csproj" />
    <ProjectReference Include="..\Sparky.Validation\Sparky.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Medino" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
