<#
.SYNOPSIS
Builds the data feeding the SQL on FHIR conformance matrix on the docs site.

.DESCRIPTION
Transforms the vendored sql-on-fhir.js test suite definitions into a compact index, and resolves
each known implementation's conformance results into the docs site's static directory — from a
local file already generated by an earlier step, a vendored/generated repo-local source, or a
fetch of its published testResultsUrl — so the conformance matrix page never depends on a
third-party host being reachable at page-view time. A failure for one implementation is recorded
as a warning and that implementation is kept in the manifest with no local results (rendered as
"no data" rather than dropped), matching the "never block publishing" behavior of the conformance
report generation step. If every implementation fails, that indicates a systemic problem (e.g.
runner network egress blocked) rather than one vendor's data being unavailable, so the script
fails loudly in that case. CI regenerates this data in the docs workflow, so none of it is
committed.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$testsDir = Join-Path $repoRoot 'test/Ignixa.SqlOnFhir.Tests/sql-on-fhir-tests/tests'
$implementationsPath = Join-Path $repoRoot 'docs/site/data/sof-implementations.json'
$staticDir = Join-Path $repoRoot 'docs/site/static'
$outDir = Join-Path $staticDir 'sof-conformance'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function Get-Slug([string]$name) {
    ($name.ToLowerInvariant() -replace '[^a-z0-9]+', '-').Trim('-')
}

function Write-CIWarning([string]$message) {
    Write-Warning $message
    Write-Host "::warning::$message"
}

# Suite index: file/title/tests[].title/tests[].tags, so the matrix can render rows without
# shipping the full test fixtures (resources, expected output) to the browser.
$suites = Get-ChildItem $testsDir -Filter '*.json' | Sort-Object Name | ForEach-Object {
    $suite = Get-Content -Raw $_.FullName | ConvertFrom-Json
    [pscustomobject]@{
        file  = $_.Name
        title = $suite.title
        tests = @($suite.tests | ForEach-Object {
            [pscustomobject]@{ title = $_.title; tags = @($_.tags) }
        })
    }
}
if ($suites.Count -eq 0) {
    Write-Host "::error::No test suites found under $testsDir — the submodule checkout may be missing or empty."
    exit 1
}

$testsOutPath = Join-Path $outDir 'tests.json'
(ConvertTo-Json -InputObject @($suites) -Depth 10) | Out-File -FilePath $testsOutPath -Encoding utf8
Write-Host "Wrote $testsOutPath ($($suites.Count) suites)"

# Implementation manifest: Ignixa's own report is already at the static root (generated by the
# conformance suite step); implementations with a sourcePath are vendored/generated repo-locally
# (no network involved); everything else is fetched and mirrored locally.
$implementations = Get-Content -Raw $implementationsPath | ConvertFrom-Json
$manifest = @()
$seenSlugs = @{}

foreach ($impl in $implementations) {
    $slug = Get-Slug $impl.name
    if ($seenSlugs.ContainsKey($slug)) {
        Write-CIWarning "Implementation '$($impl.name)' normalizes to the same slug ('$slug') as '$($seenSlugs[$slug])'; its mirrored file would overwrite the other's."
    }
    $seenSlugs[$slug] = $impl.name
    $localResultsPath = $null

    if ($impl.local -eq $true) {
        $ownReportPath = Join-Path $staticDir 'test_report.json'
        if (Test-Path $ownReportPath) {
            $localResultsPath = '/test_report.json'
        } else {
            Write-CIWarning "Local implementation '$($impl.name)' has no test_report.json at $ownReportPath"
        }
    } elseif ($impl.sourcePath) {
        $sourceFullPath = Join-Path $repoRoot $impl.sourcePath
        try {
            if (-not (Test-Path $sourceFullPath)) {
                throw "source file not found at $sourceFullPath"
            }
            $destPath = Join-Path $outDir "$slug.json"
            Copy-Item $sourceFullPath $destPath -Force
            $localResultsPath = "/sof-conformance/$slug.json"
        } catch {
            Write-CIWarning "Failed to copy local source for '$($impl.name)': $($_.Exception.Message)"
        }
    } else {
        try {
            $response = Invoke-WebRequest -Uri $impl.testResultsUrl -TimeoutSec 15 -UseBasicParsing
        } catch {
            Write-CIWarning "Failed to download '$($impl.name)' from $($impl.testResultsUrl): $($_.Exception.Message)"
            $response = $null
        }
        if ($response) {
            try {
                $null = $response.Content | ConvertFrom-Json
            } catch {
                Write-CIWarning "Response from $($impl.testResultsUrl) for '$($impl.name)' is not valid JSON: $($_.Exception.Message)"
                $response = $null
            }
        }
        if ($response) {
            try {
                $destPath = Join-Path $outDir "$slug.json"
                [System.IO.File]::WriteAllText($destPath, $response.Content, [System.Text.UTF8Encoding]::new($false))
                $localResultsPath = "/sof-conformance/$slug.json"
            } catch {
                Write-CIWarning "Failed to write mirrored file for '$($impl.name)' to ${outDir}: $($_.Exception.Message)"
            }
        }
    }

    $manifest += [pscustomobject]@{
        name             = $impl.name
        url              = $impl.url
        description      = $impl.description
        sourceUrl        = $impl.testResultsUrl
        localResultsPath = $localResultsPath
    }
}

$manifestPath = Join-Path $outDir 'manifest.json'
(ConvertTo-Json -InputObject @($manifest) -Depth 10) | Out-File -FilePath $manifestPath -Encoding utf8
$mirrored = ($manifest | Where-Object { $_.localResultsPath }).Count
Write-Host "Wrote $manifestPath ($mirrored of $($manifest.Count) implementations mirrored)"

if ($mirrored -eq 0) {
    Write-Host "::error::No implementation results could be resolved — this looks like a systemic failure (e.g. blocked network egress), not an individual vendor issue."
    exit 1
}
