<#
.SYNOPSIS
Builds the data feeding the SQL on FHIR conformance matrix on the docs site.

.DESCRIPTION
Transforms the vendored sql-on-fhir.js test suite definitions into a compact index, and mirrors
each known implementation's published test_report.json into the docs site's static directory so
the conformance matrix page never depends on a third-party host being reachable at page-view time.
A mirror failure for one implementation is recorded as a warning and that implementation is kept
in the manifest with no local results (rendered as "no data" rather than dropped), matching the
"never block publishing" behavior of the conformance report generation step. CI regenerates this
data in the docs workflow, so none of it is committed.
#>

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$testsDir = Join-Path $repoRoot 'test/Ignixa.SqlOnFhir.Tests/sql-on-fhir-tests/tests'
$implementationsPath = Join-Path $repoRoot 'docs/site/data/sof-implementations.json'
$staticDir = Join-Path $repoRoot 'docs/site/static'
$outDir = Join-Path $staticDir 'sof-conformance'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

function Get-Slug([string]$name) {
    ($name.ToLowerInvariant() -replace '[^a-z0-9]+', '-').Trim('-')
}

# Suite index: file/title/tests[].title/tests[].tags, so the matrix can render rows without
# shipping the full test fixtures (resources, expected output) to the browser.
$suites = Get-ChildItem $testsDir -Filter '*.json' | Sort-Object Name | ForEach-Object {
    $suite = Get-Content -Raw $_.FullName | ConvertFrom-Json
    [pscustomobject]@{
        file  = $_.Name
        title = $suite.title
        tests = @($suite.tests | ForEach-Object {
            [pscustomobject]@{ title = $_.title; tags = @($_.tags) }
        })
    }
}
$testsOutPath = Join-Path $outDir 'tests.json'
($suites | ConvertTo-Json -Depth 10) | Out-File -FilePath $testsOutPath -Encoding utf8
Write-Host "Wrote $testsOutPath ($($suites.Count) suites)"

# Implementation manifest: Ignixa's own report is already at the static root (generated by the
# conformance suite step); implementations with a sourcePath are vendored/generated repo-locally
# (no network involved); everything else is fetched and mirrored locally.
$implementations = Get-Content -Raw $implementationsPath | ConvertFrom-Json
$manifest = @()

foreach ($impl in $implementations) {
    $slug = Get-Slug $impl.name
    $localResultsPath = $null

    if ($impl.local -eq $true) {
        $ownReportPath = Join-Path $staticDir 'test_report.json'
        if (Test-Path $ownReportPath) {
            $localResultsPath = '/test_report.json'
        } else {
            Write-Warning "Local implementation '$($impl.name)' has no test_report.json at $ownReportPath"
        }
    } elseif ($impl.sourcePath) {
        $sourceFullPath = Join-Path $repoRoot $impl.sourcePath
        if (Test-Path $sourceFullPath) {
            $destPath = Join-Path $outDir "$slug.json"
            Copy-Item $sourceFullPath $destPath -Force
            $localResultsPath = "/sof-conformance/$slug.json"
        } else {
            Write-Warning "Source file for '$($impl.name)' not found at $sourceFullPath"
        }
    } else {
        try {
            $response = Invoke-WebRequest -Uri $impl.testResultsUrl -TimeoutSec 15 -UseBasicParsing
            $destPath = Join-Path $outDir "$slug.json"
            [System.IO.File]::WriteAllText($destPath, $response.Content, [System.Text.UTF8Encoding]::new($false))
            $localResultsPath = "/sof-conformance/$slug.json"
        } catch {
            Write-Warning "Failed to mirror '$($impl.name)' from $($impl.testResultsUrl): $($_.Exception.Message)"
        }
    }

    $manifest += [pscustomobject]@{
        name             = $impl.name
        url              = $impl.url
        description      = $impl.description
        sourceUrl        = $impl.testResultsUrl
        localResultsPath = $localResultsPath
    }
}

$manifestPath = Join-Path $outDir 'manifest.json'
($manifest | ConvertTo-Json -Depth 10) | Out-File -FilePath $manifestPath -Encoding utf8
$mirrored = ($manifest | Where-Object { $_.localResultsPath }).Count
Write-Host "Wrote $manifestPath ($mirrored of $($manifest.Count) implementations mirrored)"
