using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ignixa.Search.Sql.Generators;

/// <summary>
/// Reads the decomposed table DDL files (via AdditionalFiles) and generates SqlCatalog.BuildFromDdl()'s
/// implementation -- table/column facts sourced directly from the real DDL, not hand-transcribed.
/// </summary>
[Generator]
public sealed class SqlCatalogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var ddlFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".sql", StringComparison.OrdinalIgnoreCase))
            .Collect();

        context.RegisterSourceOutput(ddlFiles, static (spc, files) =>
        {
            if (files.Length == 0)
            {
                return;
            }

            var ddlText = string.Join(
                "\n",
                files.Select(f => f.GetText(spc.CancellationToken)?.ToString() ?? string.Empty));
            var tables = DdlTableParser.ParseTables(ddlText, SqlCatalogTableFilter.IsCatalogTable);

            spc.AddSource("SqlCatalog.g.cs", Emit(tables));
        });
    }

    private static string Emit(IReadOnlyList<DdlTable> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Ignixa.Search.Sql.Catalog;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class SqlCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    private static partial IReadOnlyDictionary<string, TableDescriptor> BuildFromDdl()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new Dictionary<string, TableDescriptor>");
        sb.AppendLine("        {");

        foreach (var table in tables)
        {
            sb.AppendLine($"            [\"{table.TableName}\"] = new TableDescriptor(\"{table.SchemaName}\", \"{table.TableName}\",");
            sb.AppendLine("            [");
            foreach (var column in table.Columns)
            {
                var maxLength = column.MaxLength.HasValue ? column.MaxLength.Value.ToString() : "null";
                var collation = column.Collation is null ? "null" : $"\"{column.Collation}\"";
                var isNullable = column.IsNullable ? "true" : "false";
                sb.AppendLine($"                new ColumnDescriptor(\"{column.Name}\", \"{column.SqlType}\", {maxLength}, {collation}, {isNullable}),");
            }
            sb.AppendLine("            ]),");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
