<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <DefineConstants>R4</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.R4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sparky.Extensions\Sparky.Extensions.csproj" />
    <ProjectReference Include="..\..\src\Sparky.SourceNodeSerialization\Sparky.SourceNodeSerialization.csproj" />
    <ProjectReference Include="..\..\src\Sparky.Specification\Sparky.Specification.csproj" />
  </ItemGroup>

</Project>
