<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.R4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sparky.Extensions\Sparky.Extensions.csproj"/>
    <ProjectReference Include="..\Sparky.SourceNodeSerialization\Sparky.SourceNodeSerialization.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Schema\FhirJsonSchemaStructureDefinitionSummaryProvider.cs" />
    <None Include="Schema\FhirJsonSchemaStructureDefinitionSummaryProvider.cs" />
  </ItemGroup>

</Project>
