// -------------------------------------------------------------------------------------------------
// Copyright (c) Ignixa Contributors. All rights reserved.
// Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// -------------------------------------------------------------------------------------------------

using System.Text.Json.Nodes;
using Ignixa.Abstractions;
using FhirCode = Ignixa.FhirFakes.Scenarios.Codes.FhirCode;

namespace Ignixa.FhirFakes.Scenarios.States;

/// <summary>
/// State that creates a MedicationRequest resource.
/// MedicationRequests represent prescriptions and medication orders.
/// </summary>
public sealed class MedicationOrderState : ScenarioState
{
    /// <summary>
    /// Gets or sets the medication code.
    /// </summary>
    public required FhirCode Code { get; init; }

    /// <summary>
    /// Gets or sets the request status ("active", "on-hold", "cancelled", "completed", "entered-in-error", "stopped", "draft", "unknown").
    /// </summary>
    public string Status { get; init; } = "active";

    /// <summary>
    /// Gets or sets the intent ("proposal", "plan", "order", "original-order", "reflex-order", "filler-order", "instance-order", "option").
    /// </summary>
    public string Intent { get; init; } = "order";

    /// <summary>
    /// Gets or sets whether this is a chronic medication (affects duration).
    /// </summary>
    public bool IsChronic { get; init; }

    /// <summary>
    /// Gets or sets the dosage instruction text.
    /// </summary>
    public string? DosageInstructions { get; init; }

    /// <summary>
    /// Gets or sets the frequency code ("once", "daily", "twice-daily", "three-times-daily", "as-needed").
    /// </summary>
    public string Frequency { get; init; } = "daily";

    /// <summary>
    /// Gets or sets the dose quantity value.
    /// </summary>
    public decimal? DoseQuantity { get; init; }

    /// <summary>
    /// Gets or sets the dose unit.
    /// </summary>
    public string? DoseUnit { get; init; }

    /// <summary>
    /// Gets or sets the duration in days for non-chronic medications.
    /// </summary>
    public int DurationDays { get; init; } = 30;

    /// <summary>
    /// Gets or sets the reason code for the prescription.
    /// </summary>
    public FhirCode? ReasonCode { get; init; }

    /// <summary>
    /// Gets or sets the attribute name of the condition this medication is treating.
    /// </summary>
    public string? ReasonConditionAttribute { get; init; }

    /// <summary>
    /// Creates a MedicationRequest resource linked to the patient and current encounter.
    /// </summary>
    public override void Execute(ScenarioContext context, SchemaBasedFhirResourceFaker faker)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(faker);

        if (context.Patient is null)
        {
            throw new InvalidOperationException("Cannot create MedicationRequest without a Patient. Ensure InitialState runs first.");
        }

        var medication = faker.Generate("MedicationRequest");
        var node = medication.MutableNode;
        var version = faker.SchemaProvider.Version;
        var isStu3 = version == FhirVersion.Stu3;
        var isR5Plus = version >= FhirVersion.R5;

        // Set required fields
        node["id"] = Guid.NewGuid().ToString();
        node["status"] = Status;
        node["intent"] = Intent;

        // Remove priority if generated by faker - 'unknown' is not valid in STU3
        // If priority is needed, it should be explicitly set via a property
        node.Remove("priority");

        // Clear any faker-generated medication choice elements first
        // (faker may have generated medicationCodeableConcept, medicationReference, or medication)
        ClearMedicationChoiceElements(node);

        // STU3/R4/R4B model medication as a medication[x] choice (CodeableConcept | Reference),
        // serialized as "medicationCodeableConcept". R5+ collapses it into a single required
        // "medication" element typed CodeableReference, whose code lives under "concept".
        var medicationCodeable = BuildCodeableConcept(Code);
        if (isR5Plus)
        {
            node["medication"] = new JsonObject { ["concept"] = medicationCodeable };
        }
        else
        {
            node["medicationCodeableConcept"] = medicationCodeable;
        }

        // Set patient reference
        node["subject"] = new JsonObject
        {
            ["reference"] = $"Patient/{context.Patient.Id}"
        };

        // Set encounter/context reference based on version
        // STU3 uses "context", R4+ uses "encounter"
        var encounterFieldName = VersionFieldOverrides.GetFieldName(version, "MedicationRequest", "encounter");

        // Clear both to avoid any conflicts
        node.Remove("encounter");
        node.Remove("context");

        if (context.CurrentEncounter is not null && !string.IsNullOrEmpty(encounterFieldName))
        {
            node[encounterFieldName] = new JsonObject
            {
                ["reference"] = $"Encounter/{context.CurrentEncounter.Id}"
            };
        }

        // Set authored date
        node["authoredOn"] = context.CurrentTime.ToString("o");

        // Set requester if practitioner is available.
        // STU3 models requester as a BackboneElement { agent (1..1), onBehalfOf } - a bare
        // reference is invalid there. R4+ flattened it to a plain Reference.
        if (context.CurrentPractitioner is not null)
        {
            var practitionerReference = new JsonObject
            {
                ["reference"] = $"Practitioner/{context.CurrentPractitioner.Id}"
            };
            node["requester"] = isStu3
                ? new JsonObject { ["agent"] = practitionerReference }
                : practitionerReference;
        }

        // Build dosage instruction with version-aware structure
        node["dosageInstruction"] = BuildDosageInstruction(isR5Plus);

        // NOTE: We intentionally do NOT include dose quantity structure because the validation
        // schema provider doesn't properly expose nested type children (value, unit, system, code)
        // for choice elements. This is a known limitation that affects all FHIR versions.
        // The text field in dosageInstruction already provides a human-readable description
        // that includes the dose information.

        // Set dispense request (for chronic meds, longer duration)
        var validityDays = IsChronic ? 365 : DurationDays;
        var dispenseQuantity = IsChronic ? 90 : DurationDays;
        var dispenseRequest = new JsonObject
        {
            ["validityPeriod"] = new JsonObject
            {
                ["start"] = context.CurrentTime.ToString("yyyy-MM-dd"),
                ["end"] = context.CurrentTime.AddDays(validityDays).ToString("yyyy-MM-dd")
            },
            ["quantity"] = new JsonObject
            {
                ["value"] = dispenseQuantity,
                ["unit"] = "tablets"
            }
        };

        // numberOfRepeatsAllowed is a positiveInt (>= 1); "no repeats" is expressed by omitting
        // it, not by a literal 0.
        var numberOfRepeatsAllowed = IsChronic ? 12 : 0;
        if (numberOfRepeatsAllowed > 0)
        {
            dispenseRequest["numberOfRepeatsAllowed"] = numberOfRepeatsAllowed;
        }

        node["dispenseRequest"] = dispenseRequest;

        // Set reason if provided.
        // STU3/R4/R4B split this into reasonCode (CodeableConcept) and reasonReference (Reference).
        // R5+ merges both into a single "reason" element typed CodeableReference, where a coded
        // reason lives under "concept" and a referenced Condition under "reference".
        if (ReasonCode is not null)
        {
            var reasonConcept = new JsonObject { ["coding"] = BuildCoding(ReasonCode) };
            if (isR5Plus)
            {
                node["reason"] = new JsonArray { new JsonObject { ["concept"] = reasonConcept } };
            }
            else
            {
                node["reasonCode"] = new JsonArray { reasonConcept };
            }
        }
        else if (!string.IsNullOrEmpty(ReasonConditionAttribute) &&
                 context.HasAttribute(ReasonConditionAttribute))
        {
            var conditionId = context.GetAttribute<string>(ReasonConditionAttribute);
            var conditionReference = new JsonObject { ["reference"] = $"Condition/{conditionId}" };
            if (isR5Plus)
            {
                node["reason"] = new JsonArray { new JsonObject { ["reference"] = conditionReference } };
            }
            else
            {
                node["reasonReference"] = new JsonArray { conditionReference };
            }
        }

        // Add to context
        context.AddMedication(medication, Code.Display);

        // NEW: Register with StateId for cross-references
        context.RegisterStateResource(StateId, medication);
    }

    private string BuildDosageText()
    {
        var frequencyText = Frequency switch
        {
            "once" => "once",
            "daily" => "once daily",
            "twice-daily" => "twice daily",
            "three-times-daily" => "three times daily",
            "as-needed" => "as needed",
            _ => Frequency
        };

        return $"Take {DoseQuantity ?? 1} {DoseUnit ?? "tablet"} {frequencyText}";
    }

    /// <summary>
    /// Clears any existing medication choice element variants from the node.
    /// This prevents validation errors from having multiple variants (e.g., both medication and medicationCodeableConcept).
    /// </summary>
    private static void ClearMedicationChoiceElements(JsonObject node)
    {
        node.Remove("medication");
        node.Remove("medicationCodeableConcept");
        node.Remove("medicationReference");
    }

    /// <summary>
    /// Builds the dosageInstruction array with version-appropriate structure.
    /// </summary>
    /// <remarks>
    /// NOTE: We intentionally do NOT include timing.repeat structure because the validation
    /// schema provider doesn't properly expose backbone element children (frequency, period, periodUnit).
    /// This is a known limitation that affects all FHIR versions. The text field provides
    /// a human-readable description of the dosage instructions.
    /// </remarks>
    private JsonArray BuildDosageInstruction(bool isR5Plus)
    {
        var dosageText = DosageInstructions ?? BuildDosageText();

        var dosage = new JsonObject
        {
            ["text"] = dosageText
        };

        // Dosage.asNeeded[x] was a boolean|CodeableConcept choice (asNeededBoolean) through R4B.
        // R5+ split it into a plain boolean "asNeeded" plus a coded "asNeededFor".
        if (Frequency == "as-needed")
        {
            if (isR5Plus)
            {
                dosage["asNeeded"] = true;
            }
            else
            {
                dosage["asNeededBoolean"] = true;
            }
        }

        return [dosage];
    }

    private static JsonObject BuildCodeableConcept(FhirCode code) => new()
    {
        ["coding"] = BuildCoding(code),
        ["text"] = code.Display
    };

    private static JsonArray BuildCoding(FhirCode code) =>
    [
        new JsonObject
        {
            ["system"] = code.System,
            ["code"] = code.Code,
            ["display"] = code.Display
        }
    ];

    /// <summary>
    /// Builds the doseQuantity node.
    /// </summary>
    private JsonObject BuildDoseQuantityNode()
    {
        return new JsonObject
        {
            ["value"] = DoseQuantity!.Value,
            ["unit"] = DoseUnit ?? "tablet",
            ["system"] = FhirCode.Systems.Ucum,
            ["code"] = DoseUnit ?? "{tbl}"
        };
    }

    /// <summary>
    /// Creates a Metformin 500mg prescription for diabetes.
    /// </summary>
    public static MedicationOrderState Metformin500mg() => new()
    {
        Code = FhirCode.Medications.Metformin500mg,
        IsChronic = true,
        Frequency = "twice-daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.DiabetesType2
    };

    /// <summary>
    /// Creates a Metformin 1000mg prescription for diabetes.
    /// </summary>
    public static MedicationOrderState Metformin1000mg() => new()
    {
        Code = FhirCode.Medications.Metformin1000mg,
        IsChronic = true,
        Frequency = "twice-daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.DiabetesType2
    };

    /// <summary>
    /// Creates a Lisinopril 10mg prescription for hypertension.
    /// </summary>
    public static MedicationOrderState Lisinopril10mg() => new()
    {
        Code = FhirCode.Medications.Lisinopril10mg,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Hypertension
    };

    /// <summary>
    /// Creates a Lisinopril 20mg prescription for hypertension.
    /// </summary>
    public static MedicationOrderState Lisinopril20mg() => new()
    {
        Code = FhirCode.Medications.Lisinopril20mg,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Hypertension
    };

    /// <summary>
    /// Creates an Amlodipine 5mg prescription for hypertension.
    /// </summary>
    public static MedicationOrderState Amlodipine5mg() => new()
    {
        Code = FhirCode.Medications.Amlodipine5mg,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Hypertension
    };

    /// <summary>
    /// Creates an Albuterol prescription for asthma.
    /// </summary>
    public static MedicationOrderState Albuterol() => new()
    {
        Code = FhirCode.Medications.Albuterol,
        IsChronic = true,
        Frequency = "as-needed",
        DoseQuantity = 2,
        DoseUnit = "puffs",
        DosageInstructions = "Inhale 2 puffs as needed for shortness of breath",
        ReasonCode = FhirCode.Conditions.Asthma
    };

    /// <summary>
    /// Creates a prenatal vitamins prescription.
    /// </summary>
    public static MedicationOrderState PrenatalVitamins() => new()
    {
        Code = FhirCode.Medications.PrenatalVitamins,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Pregnancy
    };

    /// <summary>
    /// Creates a folic acid prescription for pregnancy.
    /// </summary>
    public static MedicationOrderState FolicAcid() => new()
    {
        Code = FhirCode.Medications.FolicAcid,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Pregnancy
    };

    /// <summary>
    /// Creates an Atorvastatin 20mg prescription for hyperlipidemia.
    /// </summary>
    public static MedicationOrderState Atorvastatin20mg() => new()
    {
        Code = FhirCode.Medications.Atorvastatin20mg,
        IsChronic = true,
        Frequency = "daily",
        DoseQuantity = 1,
        DoseUnit = "tablet",
        ReasonCode = FhirCode.Conditions.Hyperlipidemia
    };

    /// <summary>
    /// Creates a Fluticasone Propionate inhaler prescription for asthma (controller medication).
    /// </summary>
    public static MedicationOrderState FluticasonePropionate() => new()
    {
        Code = FhirCode.Medications.FluticasonePropionate,
        IsChronic = true,
        Frequency = "twice-daily",
        DoseQuantity = 2,
        DoseUnit = "puffs",
        DosageInstructions = "Inhale 2 puffs twice daily for asthma control",
        ReasonCode = FhirCode.Conditions.Asthma
    };

    /// <summary>
    /// Creates a Vitamin D 50,000 IU prescription for vitamin D deficiency.
    /// </summary>
    public static MedicationOrderState VitaminD50000IU() => new()
    {
        Code = FhirCode.Medications.VitaminD50000IU,
        IsChronic = false,
        Frequency = "weekly",
        DoseQuantity = 1,
        DoseUnit = "capsule",
        DurationDays = 56,  // 8 weeks
        ReasonCode = FhirCode.Conditions.VitaminDDeficiency
    };
}
